### PR TITLE
[Bugfix] Fix draggable

### LINKED ISSUE #354: [Bug] draggable is not work
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/paimon-webui/issues) and found nothing similar.

### Paimon UI version

main

### Compute Engine

Flink

### Minimal reproduce step

edit the Catalog Table Columns

### What doesn't meet your expectations?

draggable is work

### Anything else?

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by zhangmo8**
### Purpose

close #354

### CODE REVIEW

File: paimon-web-ui/src/views/metadata/components/table-column-content/index.tsx [hunk 1]
```diff
@@ -252,9 +252,21 @@ export default defineComponent({
...
+          'modelValue': this.modelValue,
+          'onUpdate:modelValue': (value: any) => {
+            this.$props['onUpdate:modelValue']?.(value)
+          },
+          'animation': 150,
+          'handle': '.drag-handle',
+          'target': '.n-data-table-tbody',
+        },
+        {
+          default: () => <n-data-table columns={this.columns} data={this.modelValue} style={{ marginBottom: '24px' }} />,
```
Comment (SteNicholas) [inline paimon-web-ui/src/views/metadata/components/table-column-content/index.tsx:267]: Why is the `marginBottom` 24px?

Comment (zhangmo8) [reply paimon-web-ui/src/views/metadata/components/table-column-content/index.tsx:267]: Keep it some distance from the bottom of the popover box
