### PR TITLE
[Bugfix] Fix permission management

### LINKED ISSUE #403: [Bug] Permission management is not working.
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/paimon-webui/issues) and found nothing similar.

### Paimon UI version

main

### Compute Engine

Flink

### Minimal reproduce step

Users with low privileges can access all pages.

Just login!!

### What doesn't meet your expectations?

Permission management is not functioning properly, as there is a dependency relationship between parent and child nodes when selecting the role tree. When rendering the interface, it fails to render according to the permissions granted.

### Anything else?

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by hdygxsj**
### Purpose

close #403 
Permission management is not functioning properly, as there is a dependency relationship between parent and child nodes when selecting the role tree. When rendering the interface, it fails to render according to the permissions granted.

Currently, low-privilege users are able to view and access menus that they have permission for.
image

### CODE REVIEW

File: paimon-web-ui/src/store/config/type.ts [hunk 1]
```diff
@@ -16,5 +16,5 @@ specific language governing permissions and limitations
 under the License. */
 
 export type Theme = 'dark' | 'light'
-export type NavBar = 'playground' | 'cdc' | 'system' | 'settings'
+export type NavBar = 'playground' | 'cdc' | 'system' | 'settings' | 'null'
```
Comment (SteNicholas) [inline paimon-web-ui/src/store/config/type.ts:19]: Why does `NavBar` have null value?

Comment (hdygxsj) [reply paimon-web-ui/src/store/config/type.ts:19]: The front-end menu now incorporates permission management, which may result in users not having any selectable menus based on their permissions.

Comment (SteNicholas) [reply paimon-web-ui/src/store/config/type.ts:19]: @hdygxsj, I don’t think this is the reason why introduce null bar.

Comment (hdygxsj) [reply paimon-web-ui/src/store/config/type.ts]: Made some minor adjustments.

**Review by SteNicholas — APPROVED** [review]
